sudo: false

dist: trusty

language: python

python:
  - 2.7
  - 3.6

cache:
  - pip

install:
  - pip install .

before_script:
  - pip install -q flake8 pytest

script:
  - flake8 .
  - pytest -vs tests

notifications:
  email: false
